name: Build and Push Docker Image

# Триггер: при пуше в ветку main
on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Docker Buildx (для мультиплатформенной сборки)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # 4. Генерируем метаданные (теги): main-abc123, latest и др.
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/todo-flask-app
          tags: |
            type=sha,prefix=main-,suffix=-${{ github.sha }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      # 5. Собираем и пушим образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}